
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AppHeader': typeof import("../components/AppHeader.vue")['default']
    'UiAvatar': typeof import("../components/Ui/Avatar/Avatar.vue")['default']
    'UiAvatarFallback': typeof import("../components/Ui/Avatar/Fallback.vue")['default']
    'UiAvatarImage': typeof import("../components/Ui/Avatar/Image.vue")['default']
    'UiButton': typeof import("../components/Ui/Button.vue")['default']
    'UiContainer': typeof import("../components/Ui/Container.vue")['default']
    'UiDivider': typeof import("../components/Ui/Divider.vue")['default']
    'UiInput': typeof import("../components/Ui/Input.vue")['default']
    'UiLabel': typeof import("../components/Ui/Label.vue")['default']
    'UiNavbar': typeof import("../components/Ui/Navbar.vue")['default']
    'UiVeeInput': typeof import("../components/Ui/Vee/Input.vue")['default']
    'UiVeeMultiSelect': typeof import("../components/Ui/Vee/MultiSelect.vue")['default']
    'UiVueSonner': typeof import("../components/Ui/VueSonner.client.vue")['default']
    'ChessBoard': typeof import("../components/chess/Board.vue")['default']
    'ChessBoardStockfish': typeof import("../components/chess/BoardStockfish.vue")['default']
    'ChessChat': typeof import("../components/chess/Chat.vue")['default']
    'ChessOnlineBoard': typeof import("../components/chess/online/Board.vue")['default']
    'TransitionExpand': typeof import("../node_modules/.vue-transitions/TransitionExpand.vue")['default']
    'TransitionFade': typeof import("../node_modules/.vue-transitions/TransitionFade.vue")['default']
    'TransitionScale': typeof import("../node_modules/.vue-transitions/TransitionScale.vue")['default']
    'TransitionSlide': typeof import("../node_modules/.vue-transitions/TransitionSlide.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/components/index")['default']
    'Field': typeof import("vee-validate")['Field']
    'Form': typeof import("vee-validate")['Form']
    'ErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'FieldArray': typeof import("vee-validate")['FieldArray']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'UiVueSonner': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAppHeader': typeof import("../components/AppHeader.vue")['default']
    'LazyUiAvatar': typeof import("../components/Ui/Avatar/Avatar.vue")['default']
    'LazyUiAvatarFallback': typeof import("../components/Ui/Avatar/Fallback.vue")['default']
    'LazyUiAvatarImage': typeof import("../components/Ui/Avatar/Image.vue")['default']
    'LazyUiButton': typeof import("../components/Ui/Button.vue")['default']
    'LazyUiContainer': typeof import("../components/Ui/Container.vue")['default']
    'LazyUiDivider': typeof import("../components/Ui/Divider.vue")['default']
    'LazyUiInput': typeof import("../components/Ui/Input.vue")['default']
    'LazyUiLabel': typeof import("../components/Ui/Label.vue")['default']
    'LazyUiNavbar': typeof import("../components/Ui/Navbar.vue")['default']
    'LazyUiVeeInput': typeof import("../components/Ui/Vee/Input.vue")['default']
    'LazyUiVeeMultiSelect': typeof import("../components/Ui/Vee/MultiSelect.vue")['default']
    'LazyUiVueSonner': typeof import("../components/Ui/VueSonner.client.vue")['default']
    'LazyChessBoard': typeof import("../components/chess/Board.vue")['default']
    'LazyChessBoardStockfish': typeof import("../components/chess/BoardStockfish.vue")['default']
    'LazyChessChat': typeof import("../components/chess/Chat.vue")['default']
    'LazyChessOnlineBoard': typeof import("../components/chess/online/Board.vue")['default']
    'LazyTransitionExpand': typeof import("../node_modules/.vue-transitions/TransitionExpand.vue")['default']
    'LazyTransitionFade': typeof import("../node_modules/.vue-transitions/TransitionFade.vue")['default']
    'LazyTransitionScale': typeof import("../node_modules/.vue-transitions/TransitionScale.vue")['default']
    'LazyTransitionSlide': typeof import("../node_modules/.vue-transitions/TransitionSlide.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/components/index")['default']
    'LazyField': typeof import("vee-validate")['Field']
    'LazyForm': typeof import("vee-validate")['Form']
    'LazyErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'LazyFieldArray': typeof import("vee-validate")['FieldArray']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyUiVueSonner': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AppHeader: typeof import("../components/AppHeader.vue")['default']
export const UiAvatar: typeof import("../components/Ui/Avatar/Avatar.vue")['default']
export const UiAvatarFallback: typeof import("../components/Ui/Avatar/Fallback.vue")['default']
export const UiAvatarImage: typeof import("../components/Ui/Avatar/Image.vue")['default']
export const UiButton: typeof import("../components/Ui/Button.vue")['default']
export const UiContainer: typeof import("../components/Ui/Container.vue")['default']
export const UiDivider: typeof import("../components/Ui/Divider.vue")['default']
export const UiInput: typeof import("../components/Ui/Input.vue")['default']
export const UiLabel: typeof import("../components/Ui/Label.vue")['default']
export const UiNavbar: typeof import("../components/Ui/Navbar.vue")['default']
export const UiVeeInput: typeof import("../components/Ui/Vee/Input.vue")['default']
export const UiVeeMultiSelect: typeof import("../components/Ui/Vee/MultiSelect.vue")['default']
export const UiVueSonner: typeof import("../components/Ui/VueSonner.client.vue")['default']
export const ChessBoard: typeof import("../components/chess/Board.vue")['default']
export const ChessBoardStockfish: typeof import("../components/chess/BoardStockfish.vue")['default']
export const ChessChat: typeof import("../components/chess/Chat.vue")['default']
export const ChessOnlineBoard: typeof import("../components/chess/online/Board.vue")['default']
export const TransitionExpand: typeof import("../node_modules/.vue-transitions/TransitionExpand.vue")['default']
export const TransitionFade: typeof import("../node_modules/.vue-transitions/TransitionFade.vue")['default']
export const TransitionScale: typeof import("../node_modules/.vue-transitions/TransitionScale.vue")['default']
export const TransitionSlide: typeof import("../node_modules/.vue-transitions/TransitionSlide.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/components/index")['default']
export const Field: typeof import("vee-validate")['Field']
export const Form: typeof import("vee-validate")['Form']
export const ErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const FieldArray: typeof import("vee-validate")['FieldArray']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const UiVueSonner: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAppHeader: typeof import("../components/AppHeader.vue")['default']
export const LazyUiAvatar: typeof import("../components/Ui/Avatar/Avatar.vue")['default']
export const LazyUiAvatarFallback: typeof import("../components/Ui/Avatar/Fallback.vue")['default']
export const LazyUiAvatarImage: typeof import("../components/Ui/Avatar/Image.vue")['default']
export const LazyUiButton: typeof import("../components/Ui/Button.vue")['default']
export const LazyUiContainer: typeof import("../components/Ui/Container.vue")['default']
export const LazyUiDivider: typeof import("../components/Ui/Divider.vue")['default']
export const LazyUiInput: typeof import("../components/Ui/Input.vue")['default']
export const LazyUiLabel: typeof import("../components/Ui/Label.vue")['default']
export const LazyUiNavbar: typeof import("../components/Ui/Navbar.vue")['default']
export const LazyUiVeeInput: typeof import("../components/Ui/Vee/Input.vue")['default']
export const LazyUiVeeMultiSelect: typeof import("../components/Ui/Vee/MultiSelect.vue")['default']
export const LazyUiVueSonner: typeof import("../components/Ui/VueSonner.client.vue")['default']
export const LazyChessBoard: typeof import("../components/chess/Board.vue")['default']
export const LazyChessBoardStockfish: typeof import("../components/chess/BoardStockfish.vue")['default']
export const LazyChessChat: typeof import("../components/chess/Chat.vue")['default']
export const LazyChessOnlineBoard: typeof import("../components/chess/online/Board.vue")['default']
export const LazyTransitionExpand: typeof import("../node_modules/.vue-transitions/TransitionExpand.vue")['default']
export const LazyTransitionFade: typeof import("../node_modules/.vue-transitions/TransitionFade.vue")['default']
export const LazyTransitionScale: typeof import("../node_modules/.vue-transitions/TransitionScale.vue")['default']
export const LazyTransitionSlide: typeof import("../node_modules/.vue-transitions/TransitionSlide.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/components/index")['default']
export const LazyField: typeof import("vee-validate")['Field']
export const LazyForm: typeof import("vee-validate")['Form']
export const LazyErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const LazyFieldArray: typeof import("vee-validate")['FieldArray']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyUiVueSonner: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
