// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 14.06.2025, 21:25:03
const configMerger = require("C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/plugins/**/*.{js,ts,mjs}","C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/composables/**/*.{js,ts,mjs}","C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/utils/**/*.{js,ts,mjs}","C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/nuxt-chess/chess-nuxt-app/app.config.{js,ts,mjs}"] }));

module.exports = config
