// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 18.05.2025, 10:37:11
const configMerger = require("C:/Users/dalga/Desktop/programer/app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/dalga/Desktop/programer/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/programer/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/programer/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/programer/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/programer/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/programer/app/plugins/**/*.{js,ts,mjs}","C:/Users/dalga/Desktop/programer/app/composables/**/*.{js,ts,mjs}","C:/Users/dalga/Desktop/programer/app/utils/**/*.{js,ts,mjs}","C:/Users/dalga/Desktop/programer/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/programer/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dalga/Desktop/programer/app/app.config.{js,ts,mjs}"] }));

module.exports = config
